### ISSUE TITLE
NPM Dependencies are missing

### ISSUE THREAD

**Issue by maxbrokman** [jackbarham/vuejs-style-guide#1]
`package.json` doesn't seem to have all of the dependencies for this project! Vue.js isn't declared in their for example?

**Comment by jackbarham** [comment]
It all gets pulled in from `laravel-elixir-vueify`: https://github.com/JeffreyWay/laravel-elixir-vueify/blob/master/package.json

I'm doing quite a big update to this repo soon, so maybe I'll add them in manually to make it clearer.

**Comment by maxbrokman** [comment]
Well that's me told :P

**Comment by jackbarham** [comment]
No worries. I'm actually going to spend some time on this make a 'thing' as appose to something I quickly knocked up learning Vue.js - I'll will make it more verbose and obvious what is being pulled in.
