### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by kudos** [jackbarham/vuejs-style-guide#3]
I think at least some of the 22 forks on this repo are likely using this without any license. Is it open source? Can you clarify the license if it is? If not, can you make that clear also?

**Comment by jackbarham** [comment]
Sure, use this project however you like.

**Comment by dmaker3000** [comment]
Hi Jackbarham, this is real good. just stumbled upon it.
U shld make it more popular. Im sure it would
Maybe split the Css/Saas and Js part, and update to Vue2?!?

**Comment by jackbarham** [comment]
Thanks for the comment.

I'm working on a project which uses an updated version of this UI kit, all-new and rebuilt Vue.js 2.*. Once that is finished and tested I'll update this repo along with a clearer demo page. 

It's likely to be in the new year.
